CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT,
    event_name VARCHAR(255) NOT NULL,
    event_description TEXT,
    event_type VARCHAR(50) NOT NULL,
    event_location VARCHAR(155) NOT NULL,
    event_date DATE,
    event_size BIGINT,
    event_image VARCHAR(255),
    FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS palestrantes_evento (
    id_evento BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    PRIMARY KEY (id_evento, id_usuario),
    FOREIGN KEY (id_evento) REFERENCES events (id) ON DELETE CASCADE,
    FOREIGN KEY (id_usuario) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS participantes_evento (
    id_evento BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    PRIMARY KEY (id_evento, id_usuario),
    FOREIGN KEY (id_evento) REFERENCES events (id) ON DELETE CASCADE,
    FOREIGN KEY (id_usuario) REFERENCES users (id) ON DELETE CASCADE
);


INSERT INTO events (id, owner_user_id, event_name, event_description, event_type, event_location, event_date, event_size, event_image) VALUES
(101, 1, 'Dev Conference Brasil 2025', 'A maior conferência de desenvolvimento de software da América Latina. Junte-se a nós para trilhas de Java, IA, Frontend e Cloud.', 'CONFERENCIA', 'Expo Center Norte, São Paulo - SP', '2025-08-20', 500, 'https://s3.amazonaws.com/gasparbarancelli.com/javaOne_2.JPG'),
(102, 1, 'Festival de Rock de Inverno', 'Um dia inteiro com as melhores bandas de rock do cenário nacional. Muita música, food trucks e diversão.', 'SHOW', 'Arena Externa, Curitiba - PR', '2025-07-15', 1500, 'https://t.ctcdn.com.br/yx_y-18xJWSM0_zKXuQ3_Gckq58=/0x14:1008x582/640x360/smart/i379491.jpeg'),
(103, 1, 'Workshop de Teatro Improviso', 'Perca a timidez e aprenda as técnicas de improviso com o mestre Bruno. Vagas limitadas!', 'TEATRO', 'Teatro Municipal, Juiz de Fora - MG', '2025-09-05', 30, 'https://portal.uniasselvi.com.br/storage/app/noticia/1711/capa/1280x962-20230327162626-27%20de%20mar%C3%A7o%20dia%20mundial%20do%20teatro.png');

INSERT INTO palestrantes_evento (id_evento, id_usuario) VALUES
(101, 2);

INSERT INTO participantes_evento (id_evento, id_usuario) VALUES
(101, 3),
(101, 4),
(102, 4),
(103, 3);